### ISSUE TITLE
Bugs in NMODL inliner (and consistency in AST)

### ISSUE THREAD

**Issue by georgemitenkov** [BlueBrain/nmodl#667]
Consider the following NMODL:
```c++
PROCEDURE foo(a, b) {
    LOCAL m
    m = my_max(1, 3)
}

FUNCTION my_max(x, y) {
    IF (x > y) {
        my_max = x
    } else {
        my_max = y
    }
}
```
When inlining `my_max`, NMODL is
```
PROCEDURE foo(a, b) {
    LOCAL m, my_max_in_0
    {
        LOCAL x_in_0, y_in_0
        x_in_0 = 1
        y_in_0 = 3
        IF (x_in_0>y_in_0) {
            my_max_in_0 = x_in_0
        } ELSE {
            my_max_in_0 = y_in_0
        }
    }
    m = my_max_in_0
}
```

The problem is hidden in the AST structure: when inlining, last line is:
```json
"ExpressionStatement": [
                {
                  "BinaryExpression": [
                    {
                      "VarName": [
                        {
                          "Name": [
                            {
                              "String": [
                                {
                                  "name": "m"
                                }
                              ]
                            }
                          ]
                        }
                      ]
                    },
                    {
                      "BinaryOperator": [
                        {
                          "name": "="
                        }
                      ]
                    },
                    {
                      "WrappedExpression": [
                        {
                          "Name": [
                            {
                              "String": [
                                {
                                  "name": "my_max_in_0"
                                }
                              ]
                            }
                          ]
                        }
                      ]
                    }
                  ]
                }
              ]
```

When parsing, last line is 
```json

"ExpressionStatement": [
                {
                  "BinaryExpression": [
                    {
                      "VarName": [
                        {
                          "Name": [
                            {
                              "String": [
                                {
                                  "name": "m"
                                }
                              ]
                            }
                          ]
                        }
                      ]
                    },
                    {
                      "BinaryOperator": [
                        {
                          "name": "="
                        }
                      ]
                    },
                    {
                      "VarName": [
                        {
                          "Name": [
                            {
                              "String": [
                                {
                                  "name": "my_max_in_0"
                                }
                              ]
                            }
                          ]
                        }
                      ]
                    }
                  ]
                }
              ]
```

Not that in the first case `my_max_in_0` is `WrappedExpression`, and in the second - `VarName`. This inconsistency puts more pressure on the backends (handling more cases) and can introduce bugs.

Note: inliner does not seem to handle arrays as well :)
```c++
FUNCTION foo(a, b) {
    LOCAL arr[3], m
    arr[0] = 2
    bar()
    foo = arr[0]
}

PROCEDURE bar() {
    LOCAL arr[3]
    arr[0] = 0
}
```
is transformed into
```c++
FUNCTION foo(a, b) {
    LOCAL arr[3], m
    arr[0] = 2
    {
        LOCAL arr[3]
        arr[0] = 0
    }
    foo = arr[0]
}

PROCEDURE bar() {
    LOCAL arr[3]
    arr[0] = 0
}
```

**Comment by pramodk** [comment]
there are two issues mentioned above :) 

> Note that in the first case my_max_in_0 is WrappedExpression, and in the second - VarName. This inconsistency puts more pressure on the backends (handling more cases) and can introduce bugs.

Q 1.

why there is `WrappedExpression`? 

```python
    m = my_max(1, 3)
```

* Consider function call with assignment above. While inlining, we have replace `my_max(1, 3)` with function body and return value.
* In case of inlining pass as a visitor - We will visit `FunctionCall` node in the AST and we want to replace it with something else. But, if we are already visiting `FunctionCall` node then we can not replace the node itself! we must be at it's parent level and then we can replace one of the children! 
* So, in order to stop one level up, what we do is that while parsing we construct AST like:
```python
    m = WrappedExpression (my_max(1, 3))
```
i.e. all function calls we are wrapped inside `WrappedExpression`. This way, in the inlining pass we can `trap` at `WrappedExpression`, check if it contains function call and then do inlining of function call! And this is why you see `WrappedExpression` extra when there is a function.

Now, the above approach won't be required if somehow we can reach parent from children (i.e. while visiting `FunctionCall`, we can traverse to assignment statement). This was not possible two years ago but this feature has been added almost year ago! So all the wrapped expression usage can go away and we shouldn't see inconsistency.

Q2. About arrays:

> Also: inliner does not seem to handle arrays as well :)

```python
FUNCTION foo(a, b) {
    LOCAL arr[3], m
    arr[0] = 2
    {
        LOCAL arr[3]
        arr[0] = 0
    }
    foo = arr[0]
}
```

Are you referring to `arr` being redefined? I will check but if I read above code from code generation point of view then it's valid code i.e. `LOCAL arr` is redefined in another block scope and it's valid from code generation perspective?

**Comment by pramodk** [comment]
@georgemitenkov : I will check a way to avoid `WrappedExpression`. But for your case, if we "ignore" `WrappedExpression` and process underlying AST wrapped  node, would that be ok?

i.e.

```python
if(node. is_wrapped_expression())` {
     const auto& e = node.get_expression();
     //... process e  which is variable
}
```

Or, if you have visitor pass then you can just visit `visit_wrapped_expression` but then do nothing and continue visiting children:

```c++
void InlineVisitor::visit_wrapped_expression(WrappedExpression&amp; node) {   
   node.visit_children(*this);
   ...
}
```

Can you point me your usage in the code and I see if the is simple workaround is enough for time being?

**Comment by georgemitenkov** [comment]
Thank you for detailed explanation - I see why wee need `WrappedExpression` now!

For Q2, I was referring to array not bring renamed, but actually no inlined `LOCAL` variables are renamed. I guess I was looking at it from the LLVM backend point of view, where there are no scopes so we need to rename the variables:)

**Comment by georgemitenkov** [comment]
Regarding the failing kernel problem, it is here:
```c++
void InlineVisitor::visit_wrapped_expression(WrappedExpression& node) {
    node.visit_children(*this);
    const auto& e = node.get_expression();
    if (e->is_function_call()) {
        auto expression = dynamic_cast<FunctionCall*>(e.get());
        if (replaced_fun_calls.find(expression) != replaced_fun_calls.end()) {
            auto var = replaced_fun_calls[expression];
            node.set_expression(std::make_shared<Name>(new String(var)));
        }
    }
}
```
If we return the variable from the function (i.e. `VarName`), instead we now treat it as a `Name`. So what I guess we need here is to create a `VarName` instead?

**Comment by georgemitenkov** [comment]
So in JSON's output you can see that in inlining case the assignment's rhs is `Name`, not `VarName`

**Comment by pramodk** [comment]
> If we return the variable from the function (i.e. VarName), instead we now treat it as a Name. So what I guess we need here is to create a VarName instead?

I think that should be possible. Let me take a look.

**Comment by pramodk** [comment]
> Regarding the failing kernel problem, it is here:
> If we return the variable from the function (i.e. VarName), instead we now treat it as a Name. So what I guess we need here is to create a VarName instead?

```diff
→ git diff
diff --git a/ext/pybind11 b/ext/pybind11
--- a/ext/pybind11
+++ b/ext/pybind11
@@ -1 +1 @@
-Subproject commit f1abf5d9159b805674197f6bc443592e631c9130
+Subproject commit f1abf5d9159b805674197f6bc443592e631c9130-dirty
diff --git a/src/visitors/inline_visitor.cpp b/src/visitors/inline_visitor.cpp
index cb723f0f..6e818b85 100644
--- a/src/visitors/inline_visitor.cpp
+++ b/src/visitors/inline_visitor.cpp
@@ -306,7 +306,7 @@ void InlineVisitor::visit_wrapped_expression(WrappedExpression& node) {
         auto expression = dynamic_cast<FunctionCall*>(e.get());
         if (replaced_fun_calls.find(expression) != replaced_fun_calls.end()) {
             auto var = replaced_fun_calls[expression];
-            node.set_expression(std::make_shared<Name>(new String(var)));
+            node.set_expression(std::make_shared<VarName>(new Name(new String(var)), nullptr, nullptr));
         }
     }
 }
```

With this patch, I am able to run `hh.mod`. But before PR, I want to check where you have assumption of `VarName` in IR generation. Wondering if we can't handle `Name` or `VarName`. Could you point me where is problem/assumption in IR generation pass?

**Comment by georgemitenkov** [comment]
Don’t we want to also include `index` and `at` information? 

The logic is here:
https://github.com/BlueBrain/nmodl/blob/4c585f396df70bb50ed322d52554cf2c2c5a061a/src/codegen/llvm/codegen_llvm_visitor.cpp#L460

I was assuming the assignment is only possible to the `VarName` (and NMODL parser/lexer always create this node for assignments, so it’s the transformation that breaks this rule). `Name` does not have any properties, so it’s too low level for code generation and we would have to create many cases to visit this node (as it’s used nearly everywhere:) )

**Comment by pramodk** [comment]
> Don’t we want to also include index and at information?

```yaml
                   - Identifier:
                       brief: "Base class for all identifiers"
                       description: |
                               Base class for all variable types like ast::Name,    ast::PrimeName and ast::Argument.
                               \sa ast::Number etc.
...
                         - VarName:
                             members:
                               - name:
                                   brief: "Name of variable"
                                   type: Identifier
                                   node_name: true
                               - at:
                                   brief: "Value specified with `@`"
                                   type: Integer
                                   optional: true
                                   prefix: {value: "@"}
                               - index:
                                   brief: "index value in case of array"
                                   type: Expression
                                   optional: true
                                   prefix: {value: "["}
                                   suffix: {value: "]"}
                             brief: "Represents a variable"
...
                         - Name:
                             members:
                               - value:
                                   brief: "Value of name"
                                   type: String
                                   node_name: true
                             brief: "Represents a name"
..
                         - IndexedName:
                             members:
                               - name:
                                   brief: "Name of array variable"
                                   type: Identifier
                                   node_name: true
                               - length:
                                   brief: "legth of an array or index position"
                                   type: Expression
                                   prefix: {value: "["}
                                   suffix: {value: "]"}
                             brief: "Represents specific element of an array        variable"
```

I am looking at `src/language/nmodl.yaml` and we can see that `Name`, `VarName` etc are all derived from `Identifier`. `Varname` has `at` and `index` members `optional`. This means, it can also represent same thing as `Name` (i.e. we pass `nullptr` during constructor).

Some of this could be avoided but has historical context (old parser rules).

For inline visitor I can use `varName` as done in previous patch and revisit all  usages for consistency later.
